config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'home#top'
  get 'home/about' => 'home#about'
  resources :users, only: [:index, :show, :create, :edit, :update]
  resources :relationships, only: [:index, :create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
  validates :body,    length: { maximum: 200 }

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :name,    length: { in: 2..20 }
  validates :introduction,    length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  attachment :profile_image

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :username, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    if comment.save
      redirect_to book_path(book)
    else
      @book = Book.new
      @user = User.find(current_user.id)
      @book_s = Book.find(params[:book_id])
      @book_comment = comment
      render template: "books/show"
    end
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user,{only: [:edit, :update]}

def ensure_correct_user
  @book = Book.find(params[:id])
  if current_user.id != @book.user.id
   redirect_to books_path
  end
end

  def index
    @books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)
    @book_s = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: books_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: books_path)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user

  def create
    following = current_user.follow(@user)
    following.save
    redirect_back(fallback_location: users_path)
  end

  def destroy
    following = current_user.unfollow(@user)
    following.destroy
    redirect_back(fallback_location: users_path)
  end

  private
  def set_user
    @user = User.find(params[:follow_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user,{only: [:edit, :update]}

  def ensure_correct_user
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to user_path(current_user.id)
    end
  end

  def index
    @users = User.all
    @books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render 'index'
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def following
    @title = "Follow Users"
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @title = "Follower Users"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="form-user style-1 rounded has-shadow-1">
        <div class="form-header text-center">
          <h2>Editing Book</h2>
        </div>
        <div class="form-body">
          <%= form_for(@book) do |f| %>
          <div class="text-danger">
            <% if @book.errors.any? %>
            <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
            <% end %>
          </div>
          <div class="form-group has-icon">
            <p>Title</p>
            <%= f.text_field :title, autofocus: true, class:"form-control", id:"inputEmail", placeholder:""%>
            <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
          </div>
          <div class="form-group has-icon">
            <p>Opinion</p>
            <%= f.text_area :body, autofocus: true, class:"form-control", id:"inputEmail", placeholder:""%>
            <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
          </div>
          <%= f.submit "Update Book", class:"btn btn-primary" %>
          <% end %>
          <br>
          <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if @book.errors.any? %>
      <div class="text-danger">
        <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3">
      <%= render 'template/user_info', user: @user %>
      <%= render 'template/new_book', book: @book %>
    </div>
    <div class="col-xs-9">
      <%= render 'template/book_list', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if @book.errors.any? %>
      <div class="text-danger">
        <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3">
      <%= render 'template/user_info', user: @user %>
      <%= render 'template/new_book', book: @book %>
    </div>
    <div class="col-xs-9">
      <h2>Book detail</h2>
      <table class="table table-striped">
        <tbody>
          <tr>
            <td style="width:10%">
              <%= link_to user_path(@book_s.user.id) do %>
              <%= attachment_image_tag @book_s.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", class: "pull-left profile-thumb" %>
              <%= @book_s.user.name %>
              <% end %>
            </td>
            <td style="width:10%"><%= @book_s.title %></td>
            <td style="width:39%"><%= @book_s.body %></td>

            <% if @book_s.favorited_by?(current_user) %>
            <td style="width:6%">
              <%= link_to book_favorites_path(@book_s), method: :delete do %>
              <span class="glyphicon glyphicon-heart" style="color: red;"></span>
              <%= @book_s.favorites.count %>
              <% end %>
            </td>
            <% else %>
            <td style="width:6%">
              <%= link_to book_favorites_path(@book_s), method: :post do %>
              <span class="glyphicon glyphicon-heart-empty"></span>
              <%= @book_s.favorites.count %>
              <% end %>
            </td>
            <% end %>
            <td style="width:15%">コメント数：<%= @book_s.book_comments.count %></td>
            <% if @book_s.user == current_user %>
            <td style="width:10%">
              <%= link_to edit_book_path(@book_s) do %>
              <button type="button" class="btn btn-success"><span>Edit</span></button>
              <% end %>
            </td>
            <td style="width:10%">
              <%= link_to book_path(@book_s), method: :delete, "data-confirm" => "Are you sure?" do %>
              <button type="button" class="btn btn-danger"><span>Destroy</span></button>
              <% end %>
            </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <table class="table table-hover">
        <tbody>
          <% @book_s.book_comments.each do |book_comment| %>
          <tr>
            <td style="width:8%">
              <%= link_to user_path(@book_s.user.id) do %>
              <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40', class: "pull-left profile-thumb" %>
              <%= book_comment.user.name %>
              <% end %>
            </td>
            <td style="width:82%">
              <span class="comment-date"><%= book_comment.created_at.strftime('%Y/%m/%d') %></span>
              <div class="comment-entry"><%= book_comment.comment %></div>
            </td>
            <td style="width:10%">
              <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% if @book_comment.errors.any? %>
      <div class="text-danger">
        <h2><%= @book_comment.errors.count %> errors prohibited this obj from being saved:</h2>
        <ul>
          <% @book_comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <%= form_for [@book_s, @book_comment] do |f| %>
      <div class="row">
        <div class="col-sm-12">
          <%= f.text_area :comment, rows:'2', class: "form-control",placeholder: "コメント" %>
        </div>
      </div>
      <%= f.submit "送信", class: "btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="body">
  <div class="container">
    <h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-md-6">

      <h1>
        welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>  !!
      </h1>
      <p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,<br>
        you can share and exchange your opinions , inpressions , and emotions<br>
      about various books!</p>

      <div class="btn-wrapper">
        <% if user_signed_in? %>
        <div class="row">
          <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/<% current_user.id %>">Log in</a></p>
        </div>
        <div class="row">
          <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/<% current_user.id %>">Sign Up</a></p>
        </div>
        <% else %>
        <div class="row">
          <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
        </div>
        <div class="row">
          <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <p class="navbar-brand">Bookers</p>
        </div>
        <div class="collapse navbar-collapse" id="navbarEexample1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id) do %>
              <span class="glyphicon glyphicon-home"> Home </span>
              <% end %>
            </li>
            <li>
              <%= link_to users_path do %>
              <span class="glyphicon glyphicon-user"> Users </span>
              <% end %>
            </li>
            <li>
              <%= link_to books_path do %>
              <span class="glyphicon glyphicon-book"> Books </span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out"> logout </span>
              <% end %>
            </li>
            <% else %>
            <li>
              <%= link_to root_path do %>
              <span class="glyphicon glyphicon-home"> Home </span>
              <% end %>
            </li>
            <li>
              <%= link_to '/home/about' do %>
              <span class="glyphicon glyphicon-link"> About </span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
              <span class="glyphicon glyphicon-edit"> sign up </span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in"> login </span>
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
  <% end %>
  <% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
  <% end %>

  <%= yield %>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-offset-9 col-md-3">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/template/_book_list.html.erb
<h2>Books</h2>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr>
      <td style="width:10%">
        <%= link_to user_path(book.user.id) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40', class: "pull-left profile-thumb" %>
        <% end %>
      </td>
      <td style="width:20%"><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
      <td style="width:49%"><%= book.body %></td>
      <% if book.favorited_by?(current_user) %>
      <td style="width:6%">
        <%= link_to book_favorites_path(book), method: :delete do %>
        <span class="glyphicon glyphicon-heart" style="color: red;"></span>
        <%= book.favorites.count %>
        <% end %>
      </td>
      <% else %>
      <td style="width:6%">
        <%= link_to book_favorites_path(book), method: :post do %>
        <span class="glyphicon glyphicon-heart-empty"></span>
        <%= book.favorites.count %>
        <% end %>
      </td>
      <% end %>
    <td style="width:15%">コメント数：<%= book.book_comments.count %>
    </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/template/_new_book.html.erb
<h2>New book</h2>
<%= form_for(book, url: books_path) do |f| %>
<p>Title</p>
<%= f.text_field :title, class:"form-control" %>
<br>
<p>Opinion</p>
<%= f.text_area :body, class:"form-control", rows:"3" %>
<br>
<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
<% end %>

app/views/template/_user_info.html.erb
<div class="clearfix">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 120, 120, format: 'jpeg', class: "profile-img", fallback: "no_image.jpg" %>
  <br>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <td>name</td>
        <td class="overflow-wrap-break"><%= user.name %></td>
      </tr>
      <tr>
        <td>introduction</td>
        <td class="overflow-wrap-break"><%= user.introduction %></td>
      </tr>
      <tr>
        <td>follows</td>
        <td class="overflow-wrap-break">
          <%= link_to following_user_path(user.id) do %>
          <%= user.followings.count %>
            <% end %>
          </td>
      </tr>
      <tr>
        <td>followers</td>
        <td class="overflow-wrap-break">
          <%= link_to followers_user_path(user.id) do %>
          <%= user.followers.count %>
            <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <% if user.id == current_user.id %>
  <%= link_to edit_user_path(user) do %>
  <button type="button" class="btn btn-default col-xs-12" aria-label="Left Align"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
  <% end %>
  <% end %>
</div>
<% unless current_user == user %>
<% if current_user.following?(user) %>
<%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
<%= hidden_field_tag :follow_id, user.id %>
<%= f.submit 'フォロー外す', class: 'btn btn-primary btn-block' %>
<% end %>
<% else %>
<%= form_for(current_user.relationships.build) do |f| %>
<%= hidden_field_tag :follow_id, user.id %>
<%= f.submit 'フォローする', class: 'btn btn-success btn-block' %>
<% end %>
<% end %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2>User info</h2>
      <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
      <div class="text-danger">
        <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class="form-group has-icon">
        <label class="control-label sr-only" for="inputEmail">Name</label>
        <p>Name</p>
        <%= f.text_field :name, autofocus: true, id:"inputEmail", placeholder:""%>
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
      </div>
      <div class="form-group has-icon clearfix">
        <p>Image</p>
        <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
      </div>
      <div class="form-group has-icon">
        <label class="control-label sr-only" for="inputEmail">introduction</label>
        <p>Introduction</p>
        <%= f.text_area :introduction, autofocus: true, id:"inputEmail", placeholder:""%>
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
      </div>
      <%= f.submit "Update User", class:"btn btn-primary mt-20" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <% if @book.errors.any? %>
    <div class="text-danger">
      <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-xs-3">
      <%= render 'template/user_info', user: @user %>
      <%= render 'template/new_book', book: @book %>
    </div>
    <div class="col-xs-9">
      <h2>Users</h2>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th style="width:15%">image</th>
            <th style="width:15%">name</th>
            <th style="width:15%"></th>
            <th style="width:20%"></th>
            <th style="width:10%"></th>
            <th style="width:25%"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'60x60', class: "pull-left profile-thumb" %></td>
            <td><%= user.name %></td>
            <td>フォロー数：<%= user.followings.count %></td>
            <td>フォロワー数：<%= user.followers.count %></td>
            <td>
              <% unless current_user == user %>
              <% if current_user.following?(user) %>
              <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
              <%= hidden_field_tag :follow_id, user.id %>
              <%= f.submit 'フォロー外す', class: 'btn btn-xs btn-primary btn-block' %>
              <% end %>
              <% else %>
              <%= form_for(current_user.relationships.build) do |f| %>
              <%= hidden_field_tag :follow_id, user.id %>
              <%= f.submit 'フォローする', class: 'btn btn-xs btn-success btn-block' %>
              <% end %>
              <% end %>
              <% end %>
            </td>
            <td><%= link_to user_path(user.id) do %>Show<% end %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if @book.errors.any? %>
      <div class="text-danger">
        <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-3">
      <%= render 'template/user_info', user: @user %>
      <%= render 'template/new_book', book: @book %>
    </div>
    <div class="col-xs-9">
      <%= render 'template/book_list', books: @books %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2><%= @title %></h2>
      <% if @users.empty? %>
        <p>ユーザーはいません</p>
        <% else %>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th style="width:15%">image</th>
              <th style="width:15%">name</th>
              <th style="width:15%"></th>
              <th style="width:20%"></th>
              <th style="width:35%"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'60x60', class: "pull-left profile-thumb" %></td>
              <td><%= user.name %></td>
              <td>フォロー数：<%= user.followings.count %></td>
              <td>フォロワー数：<%= user.followers.count %></td>
              <td><%= link_to user_path(user.id) do %>Show<% end %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <% end %>
      </div>
    </div>
  </div>